---
- name: set up user
  ansible.windows.win_user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    password_never_expires: true
    state: present
    groups:
      - Administrators
